FROM maven as build
WORKDIR /build
COPY . .
RUN mvn clean package

FROM openjdk:22-jdk-slim as run
WORKDIR /app
COPY --from=build ./build/target/*.jar ./app.jar
EXPOSE 8080
ENTRYPOINT java -jar app.jar
